name: CI

on:
  push:
    branches: [staging, mainnet]
  pull_request:

jobs:
  wiki_address_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun 1.0.29
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.29

      - run: bun install --frozen-lockfile

      - name: Run wikiCheck
        run: bun run wikiCheck
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun 1.0.29
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.29

      - run: bun install --frozen-lockfile

      - name: Run tests
        run: bun run test:parallel

  deploy:
    runs-on: ubuntu-latest
    # TODO: reenable
    if: false
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Run deploy
        run: yarn test:deploy
        env:
          BATCH_GATEWAY_URLS: '["https://universal-offchain-unwrapper.ens-cf.workers.dev/"]'
